### ISSUE TITLE
Backspace

### ISSUE THREAD

**Issue by xxc3nsoredxx** [gwoplock/ExOS#17]
Backspacing doesn't work quite right.

**Comment by gwoplock** [comment]
Where exactly does it happen?

**Comment by xxc3nsoredxx** [comment]
I noticed it when I was testing after doing the newlines stuff. When it's booted up and you hit backspace, it doesn't actually backspace. I haven't investigated it, but I think the issue might be when it adds the null character behind the cursor. It moves the cursor forward after.

**Comment by gwoplock** [comment]
I’ve used backspace before and it works so I’ll take a look too. So it only happens to the text printed during boot?

**Comment by xxc3nsoredxx** [comment]
Something probably changed as a result of the newlines. Make sure you test with that branch.

**Comment by xxc3nsoredxx** [comment]
Should be fixed now.
